AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.

Globals:
  Function:
    Timeout: 10

Parameters:
  UserPoolId:
    Type: String
    Description: The Cognito User Pool ID
  ClientId:
    Type: String
    Description: The Cognito Client ID
  ClientSecret:
    Type: String
    Description: The Cognito Client Secret
    NoEcho: true

Resources:
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Authentication/
      Handler: SignUp.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref ExceptionsLayer
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPoolId
          CLIENT_ID: !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonCognitoPowerUser
      Events:
        SignUp:
          Type: Api
          Properties:
            Path: /signup
            Method: post

  ExceptionsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ExceptionsLayer
      Description: Lambda layer for exceptions
      ContentUri: layers/Exceptions/
      CompatibleRuntimes:
        - python3.8

Outputs:
  SignUpApi:
    Description: "API Gateway endpoint URL for SignUp function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/signup/"
