AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.

Globals:
  Function:
    Timeout: 10
    Architectures:
      - arm64
    Runtime: python3.9

Parameters:
  UserPoolId:
    Type: String
    Description: The Cognito User Pool ID
  ClientId:
    Type: String
    Description: The Cognito Client ID
  ClientSecret:
    Type: String
    Description: The Cognito Client Secret
    NoEcho: true

Resources:
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Authentication/
      Handler: SignUp.lambda_handler
      Layers:
        - !Ref ExceptionsLayer
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPoolId
          CLIENT_ID: !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonCognitoPowerUser
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /authentication/signup
            Method: post

  SignInFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Authentication/
      Handler: SignIn.lambda_handler
      Layers:
        - !Ref ExceptionsLayer
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPoolId
          CLIENT_ID: !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonCognitoPowerUser
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /authentication/signin
            Method: post

  VerifyConfirmationCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Authentication/
      Handler: VerifyConfirmationCode.lambda_handler
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPoolId
          CLIENT_ID: !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonCognitoPowerUser
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /authentication/verifyconfirmationcode
            Method: post

  GetEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Search/
      Handler: SearchLambdas.get_events
      Layers:
        - !Ref ExceptionsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /search/events
            Method: get

  GetVenuesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Search/
      Handler: SearchLambdas.get_venues
      Layers:
        - !Ref ExceptionsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /search/venues
            Method: get

  GetOrganisersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Search/
      Handler: SearchLambdas.get_organisers
      Layers:
        - !Ref ExceptionsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /search/organisers
            Method: get

  GetEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Search/
      Handler: GetSpecificLambdas.get_event
      Layers:
        - !Ref ExceptionsLayer
        - !Ref DatabaseLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /search/event/{event_id}
            Method: get


  GetOrganiserEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Search/
      Handler: GetSpecificLambdas.get_organiser_events
      Layers:
        - !Ref ExceptionsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /search/organiser
            Method: get

  GetVenueEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Search/
      Handler: GetSpecificLambdas.get_venue_events
      Layers:
        - !Ref ExceptionsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /search/venue/{venue_id}
            Method: get

  ReserveListingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Listings/Reserve/
      Handler: CreateReservation.lambda_handler
      Layers:
        - !Ref ExceptionsLayer
        - !Ref DatabaseLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        TicketstarApi:
          Type: Api
          Properties:
            Path: /listings/reserve
            Method: post

  ExceptionsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ExceptionsLayer
      Description: Lambda layer for exceptions
      ContentUri: layers/Exceptions/
      CompatibleRuntimes:
        - python3.9
  DatabaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DatabaseLayer
      Description: Contains database functions and exceptions
      ContentUri: layers/Database
      CompatibleRuntimes:
        - python3.9

Outputs:
  TicketstarApi:
    Description: "API Gateway endpoint URL for Prod stage for ticketstar function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
